server:
    port: 8083
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/ams
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        maxPoolPreparedStatementPerConnectionSize: 20
        
mybatis: 
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.jiuyescm.ams.mapper
    
logging:
    level:
        org.mybatis: DEBUG